# Generated by Django 4.0.3 on 2022-04-08 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, through='calendar_app.UserEvent', to=settings.AUTH_USER_MODEL),
        ),
    ]
