# Generated by Django 4.0.3 on 2022-04-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_event_unique_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='official_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
