# Generated by Django 4.0.3 on 2022-04-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_userevent_official_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.country'),
        ),
    ]
