# Generated by Django 4.0.3 on 2022-04-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_remove_userevent_official_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.notification'),
        ),
    ]
